standingsURL: https://espndeportes.espn.com/futbol/posiciones/_/liga/arg.1
fixtureURL: https://espndeportes.espn.com/futbol/equipo/calendario/_/id/16/river-plate
scorerStatsURL: https://www.espn.com.ar/futbol/equipo/estadisticas/_/id/16/liga/ARG.1/vista/anotaciones
cardStatsURL: https://www.espn.com.ar/futbol/equipo/estadisticas/_/id/16/liga/ARG.1/vista/tarjetas
time_zone_1: America/New_York
time_zone_2: America/Argentina/Buenos_Aires
fileToUpload: proximo-partido.png
font: NotoSansCJK-Regular.ttc
font_color: white
log_file: bot.log
log_level: INFO
subreddit: 'CARiverPlateTest'