standingsURL: https://www.espn.com.ar/futbol/posiciones/_/liga/arg.copa_lpf
fixtureURL: https://espndeportes.espn.com/futbol/equipo/calendario/_/id/16/river-plate
scorerStatsURL: https://www.espn.com.ar/futbol/equipo/estadisticas/_/id/16/liga/ARG.1/vista/anotaciones
cardStatsURL: https://www.espn.com.ar/futbol/equipo/estadisticas/_/id/16/liga/ARG.1/vista/tarjetas
time_zone_1: America/New_York
time_zone_2: America/Argentina/Buenos_Aires
fileToUpload: proximo-partido.png
font: NotoSansCJK-Regular.ttc
font_color: white
log_file: bot.log
log_level: INFO
subreddit: 'CARiverPlateTest'
name_to_file:
  Acassuso: 'acassuso.png'
  Agropecuario: 'agropecuario-argentino.png'
  Aldosivi: 'aldosivi.png'
  Almirante Brown: 'almirante-brown.png'
  Argentine Copa de la Liga Profesional: 'lpf-2.png'
  Argentinos Juniors: 'argentinos.png'
  Arsenal de Sarandí: 'arsenal.png'
  Atlético Tucumán: 'atleticotucuman.png'
  Atlético-MG: 'atletico-mg.png'
  Banfield: 'banfield.png'
  Barracas Central: 'barracas-central.png'
  Belgrano (Córdoba): 'belgrano-cordoba.png'
  Boca Juniors: 'bocajuniors.png'
  Brown (Adrogué): 'brown-de-adrogue.png'
  Cambaceres: 'cambaceres.png'
  Central Córdoba (Rosario): 'central-cordoba-r.png'
  Central Córdoba (Santiago del Estero): 'centralcordoba.png'
  Central Norte: 'central-norte-de-salta.png'
  Chaco For Ever: 'chaco-for-ever.png'
  Cipolletti: 'cipolletti.png'
  Club Friendly: 'amistoso.png'
  Colegiales: 'colegiales.png'
  Colón (Santa Fe): 'colon.png'
  Copa Argentina: 'copa-argentina-2.png'
  Copa Libertadores: 'libertadores-2.png'
  Defensa y Justicia: 'defensayjusticia.png'
  Deportivo Laferrere: 'deportivo-laferrere-ok.png'
  Deportivo Madryn: 'deportivo-madryn.png'
  Deportivo Morón: 'dep-moron.png'
  Dock Sud: 'dock-sud.png'
  Estudiantes de La Plata: 'estudiantes.png'
  Ferro Carril Oeste: 'ferro-carril-oeste.png'
  Flandria: 'flandria.png'
  Gimnasia (Mendoza): 'gimnasia-esgrima-m.png'
  Gimnasia La Plata: 'gimnasia.png'
  Gimnasia y Esgrima (Jujuy): 'gimnasia-jujuy.png'
  Gimnasia y Tiro (Salta): 'gimnasia-y-tiro-salta.png'
  Godoy Cruz Antonio Tomba: 'godoycruz.png'
  Güemes: 'guemes.png'
  Huracán: 'huracan.png'
  Independiente: 'independiente.png'
  Independiente Rivadavia: 'independiente-riv-m.png'
  Ituzaingó: 'ituzaingo.png'
  JJ Urquiza: 'justo-jose-de-urquiza.png'
  Lanús: 'lanus.png'
  Liniers: 'liniers.png'
  Los Andes: 'los-andes.png'
  Newell's Old Boys: "newells.png"
  Olimpo: 'club-olimpo.png'
  Otamendi: 'otamendi.png'
  Patronato: 'patronato.png'
  Platense: 'platense.png'
  Puerto Nuevo: 'puerto-nuevo.png'
  Quilmes: 'quilmes.png'
  Racing (Córdoba): 'racing-de-cordoba.png'
  Racing Club: 'racing.png'
  River Plate: 'riverplate.png'
  Rosario Central: 'rosariocentral.png'
  Sacachispas: 'sacachispas.png'
  San Lorenzo: 'sanlorenzo.png'
  San Martín (Tucumán): 'san-martin-t.png'
  Sarmiento (Junín): 'sarmiento.png'
  Sol de Mayo (Viedma): 'sol-de-mayo-viedma-ok.png'
  Sportivo Las Parejas: 'sportivo-las-parejas.png'
  Sportivo Peñarol: 'sportivo-penarol.png'
  Talleres (Córdoba): 'talleres.png'
  Tigre: 'tigre.png'
  Tristán Suárez: 'tristan-suarez.png'
  Unión (Santa Fe): 'union.png'
  Vélez Sarsfield: 'velez.png'